#!/bin/sh
cd "${0%/*}" || exit                                    # Run from this directory

rm -r temp
rm -r report
foam_template/Allclean

#------------------------------------------------------------------------------
