# =====================================================================================
#                       Subdirectory
# =====================================================================================
set(SOLVERS ${APPLICATIONS}/solvers)
add_subdirectory(${SOLVERS})
set(UTLITIES ${APPLICATIONS}/utilities)
add_subdirectory(${UTLITIES})
