#!/bin/sh
cd "${0%/*}" || exit                                    # Run from this directory
source ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions       # OpenFOAM run functions
source ${OXYSIM_REPO_ROOT:?}/bin/tools/STFSRunFunctions # Override runApplication function for testing
#------------------------------------------------------------------------------

# Function to print usage
usage() {
  echo "Usage: $0 [-p|--parallel] [-h|--help]"
  echo "  -h, --help        Display this help message"
  exit 1
}

# Parse command line arguments
while [[ "$#" -gt 0 ]]; do
  case $1 in
    -h|--help)
      usage
      ;;
    --) # End of all options
      shift
      break
      ;;
    -*|--*) # Unsupported options
      echo "Unknown option: $1"
      usage
      ;;
    *) # End of options, remaining are positional arguments
      break
      ;;
  esac
  shift
done

#------------------------------------------------------------------------------
# run application
runApplication blockMesh
# copy initial time step
cp -r 0.org 0

echo "Running single core..."
runApplication $(getApplication)

exit 0

#------------------------------------------------------------------------------
