#!/bin/bash
# source shared shell helpers
source "$(dirname "${BASH_SOURCE[0]}")/../../../scripts/bash_functions.sh"

printNiceHeader "test flameletThermo"

# Perform test
error_code=0

# run executable
cd case || error_code=1
./Allclean || error_code=1
./Allrun || error_code=1
cd -
exit $error_code
