#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase
rm -r 0 || error_code=0
rm constant/flameletProperties || error_code=0
#------------------------------------------------------------------------------

